"""Init

Revision ID: da9704b809cd
Revises: 
Create Date: 2024-03-08 14:09:52.182852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9704b809cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('mark', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('modelYear', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=False),
    sa.Column('bodywork', sa.String(), nullable=False),
    sa.Column('package', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto')
    # ### end Alembic commands ###
